"""Shared constants for the DAH Flawless MVP."""

DEFAULT_SEED = 42
DEFAULT_ROUNDS = 5

CONFIDENCE_THRESHOLD = 0.60
DETECTION_WINDOW = 2
AVAIL_FLOOR = 0.50
RECOVERY_TARGET = 0.70
RECOVERY_WINDOW = 2

BASE_TIMESTAMP = 1_710_001_200
ROUND_SECONDS = 60

SCRIPTED_ATTACKS = (
    "PRIORITY_POISONING",
    "TELEMETRY_FDI",
    "TIME_DESYNC_REPLAY",
)
