[theme]
base = "dark"
primaryColor = "#e8412f"
backgroundColor = "#05070b"
secondaryBackgroundColor = "#0a0e14"
textColor = "#d6dae1"
font = "monospace"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
